import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Container } from "@/components/Container";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >

      <body className="">
        {/* <div >
        <div className="p-6">
          <h1 className="mb-6">
            texto especial em todas as rotas
          </h1>
          <hr/>
          <hr/>
        </div>
      </div> */}
         <Container>
          <Header/>
               {children}
            <footer className="text-6xl font-bold text-center py-8">
                <p>
                    e aqui a marca, o logotipo e marca registrada...
                </p>
            </footer>
            </Container>
        </body>
    </html>
  );
}
