import type { Metadata } from "next";
import "./globals.css";
import { Container } from "@/components/Container";
import Header from "@/components/Header";
import { Footer } from "@/components/Footer";





export const metadata: Metadata = {
  title:{
    default:'The Blog - Este é um Blog com nextjs',
    template: '%s | The Blog'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >

      <body className="bg-red-500 text-white p-10">
        {/* <div >
        <div className="p-6">
          <h1 className="mb-6">
            texto especial em todas as rotas
          </h1>
          <hr/>
          <hr/>
        </div>
      </div> */}
         <Container>
          <Header/>
               {children}
            <Footer/>
            </Container>
        </body>
    </html>
  );
}
